[package]
name = "mdbook-minijinja"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["string"]}
env_logger = "0.11.5"
log = "0.4.22"
mdbook = "0.4.40"
minijinja = {version = "2.4.0", features = ["loader"]}
semver = "1.0.23"
serde = "1.0.214"
serde_json = "1.0.132"
toml = "0.8.19"
